# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models

def fill_layer_source(apps, schema_editor):
    try:
        Layer = apps.get_model("gvsigol_services", "Layer")
        for layer in Layer.objects.all():
            try:
                if not layer.source_name and layer.datastore and layer.datastore.type == 'v_PostGIS':
                    layer.source_name = layer.name
                    layer.save()
            except Exception as error:
                print "\n    ** Error gvsigol: Error asignando layer_source"
                print layer.pk
                print error
    except Exception as error:
        print "\n    ** Error gvsigol: Error asignando layer_source"
        print error
        
class Migration(migrations.Migration):
    dependencies = [
        ('gvsigol_services', '0033_layer_source_name'),
        ('gvsigol_services', '0036_auto_20200731_1850'),
    ]

    operations = [
        migrations.RunPython(fill_layer_source, reverse_code=migrations.RunPython.noop)
    ]
